### ISSUE TITLE
SDS-004: PostgreSQL database backup is performed regularly and automatedly 

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/OMOP#53]
## Description
There must be a backup policy in place as per SRS-007.

## Linked Issues
#10 

## Requirements
1. A script must be written to run rsync or equivalent command to perform a backup of PostgreSQL database which is run monthly.
2. The script must be automated to run monthly.
3. Instructions on how to use the script, the backup and the recovery plan must be documented

## Acceptance Criteria
- [ ] A script successfuly performs a copy action to a separate storage space which is independent of the server used for hosting the PostgreSQL
- [ ] A task must be set up to run the backup script periodically
- [ ] There must exist documentation on backup snd recovery plan

## Testing Guidance
1. run the backup script
2. ensure backup is performed successfully
3. ensure backup file can be used to restore PostgreSQL database
