### ISSUE TITLE
SDS-009: The CSC OMOP`ProjectManager`

### ISSUE THREAD

**Issue by dangerdika** [GSTT-CSC/OMOP#58]
## Description
This issue defines ProjectManager behaviour in the CSC OMOP databse. The purpose of the ProjectManager is to process and validate management tasks as outlined below.

## Linked Issues
#14 
#15 
#30 

## Requirements
1. Must instantiate `ProjectManager` class
2. Must allow `ProjectManager` to perform the tasks outlined in the acceptance criteria

## Acceptance Criteria
- [ ] `ProjectManager` validates new project requests e.g., based on required standardised directory structure, file names, required project-specific YAML file containing mandatory and optional details, etc.
- [ ] The `ProjectManager` can output a one-pager summary of the project's key details e.g., a PDF.
- [ ] #78
- [ ] #77
- [ ] The `ProjectManager` can generate queries e.g., SQL, XNAT API, ElasticSearch i.e., CogStack, etc., that can be run on the service's database component.
- [ ] The 'ProjectManager` has PostgreSQL constraints enabled to enforce naming and schema conventions, including entity relationships.
- [ ] Documentation of details on the functionality and usage of `ProjectManager` is available on the service's core GitHub repository e.g., Read The Docs, GitHub Wiki, etc.

## Testing Guidance
- A pytest must be included for each ProjectManager task
- A pytest for each task must pass
