### ISSUE TITLE
SDS-012-1 Upload a directory of DICOMs to orthanc as part of test framework

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/OMOP#71]
## Description
> Provide a short description on what the design specification is, why it's required, and any technical tradeoffs and considerations, and the proposed approach. If there is any associated documentation, literature, etc., please link it here and include pseudo-code snippets if helpful.

As part of our automated testing framework we will use orthanc as a test PACS system. We need an automated script for populating orthanc with test data.

## Linked Issues
> SDS issues are typically created from an Acceptance Criteria checklist item from System Requirement Specification (SRS) issues. However, if helpful, you can tag the other SRS issues that are related to this SDS issue if helpful.

#61 

## Requirements
>Provide a numbered list of design requirements e.g., what technical development should broadly aim to achieve, such as:
>
1. A script (bash or python) for uploading a directory of DICOM data to orthanc

## Acceptance Criteria
>Provide a checklist of acceptance criteria i.e., technical changes to the code, database, etc. that successfully covers the above requirements, and should ideally be testable by `pytest` (or any other testing framework).

- [ ] a directory of a single DICOM series can be uploaded to orthanc
- [ ] a directory of multiple DICOM series in a nested structure cna be uploaded to orthanc
- [ ] the PACS destination can be configured externally (through input argument or environment variables)

## Testing Guidance
>Provide guidance on how to test for the above success criteria, including testing frameworks, such as:
>
>- Run the Docker container, open a Chrome web browser, navigate to localhost, and manually upload .csv files to database tables via pgAdmin4
>- Run `pytest tests/`

**Comment by heyhaleema** [comment]
@sophie22 [This](https://orthanc.uclouvain.be/book/users/docker.html) might be of interest.
